.TH "include/ Directory Reference" 3 "26 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbarcode.inc\fP"
.br
.RI "\fIFunctions for the handling of different barcodes. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBform.inc\fP"
.br
.RI "\fIFunctions for outputting the Barcode entry form. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBpear.inc\fP"
.br
.RI "\fIMakes PEAR work with extentions installed in the home directory. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBproduct.inc\fP"
.br
.RI "\fIFunctions to output Product Info. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fButils.inc\fP"
.br
.RI "\fIHelpful Utilities. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBxmlrpc.inc\fP"
.br
.RI "\fIXML-RPC Library. \fP"
.PP

.in -1c
