.TH "include/barcode.inc" 3 "5 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/barcode.inc \- Functions for the handling of different barcodes. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcheckBarcode\fP ($barcode)"
.br
.ti -1c
.RI "\fBgetBarcodeInfo\fP ($barcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for the handling of different barcodes. 

This file currently deals with the handling of barcodes and getting the information associated with them. 
.PP
Definition in file \fBbarcode.inc\fP.
.SH "Function Documentation"
.PP 
.SS "checkBarcode ($ barcode)"
.PP
Checks to see if a valid, handalable, barcode was entered. 
.PP
\fBParameters:\fP
.RS 4
\fI$barcode\fP The Barcode to be checked 
.RE
.PP
\fBReturns:\fP
.RS 4
The type of barcode entered if valid, FALSE if it is not 
.RE
.PP

.PP
Definition at line 17 of file barcode.inc.
.PP
References XMLRPC_prepare(), and XMLRPC_request().
.PP
.nf
17                                 {
18   switch ($_GET['type']) {
19     case 'upc':
23       $result = XMLRPC_request('dev.upcdatabase.com', '/rpc', 'lookupUPC', array(XMLRPC_prepare($barcode)));
24       if ($result[1] != 'Error: Invalid length') {
25         if (strlen($barcode) == 12) {
26           return 'upca';
27         }
28         else if (strlen($barcode) == 13) {
29           return 'ean13';
30         }
31         else {
32           return FALSE;
33         }
34       }
35       else {
36         return FALSE;
37       }
38       break;
39     case 'isbn':
40       if (strlen($barcode) == 10) {
41         return 'isbn';
42       }
43       else if (strlen($barcode) == 13) {
44         return 'bookland';
45       }
46       else {
47         return FALSE;
48       }
49       break;
50   }
51 }
.fi
.PP
.SS "getBarcodeInfo ($ barcode)"
.PP
Output Barcode Info 
.PP
\fBParameters:\fP
.RS 4
\fI$barcode\fP The barcode to lookup 
.RE
.PP
\fBReturns:\fP
.RS 4
HTML code to create the info area 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBcheckBarcode\fP 
.RE
.PP

.PP
Definition at line 59 of file barcode.inc.
.PP
References getImages(), parseXML(), XMLRPC_prepare(), and XMLRPC_request().
.PP
.nf
59                                   {
60   switch ($_GET['type']) {
61     case 'upc':
65       $output = '';
66       $output .= '<div id='upc'>';
67       $output .= '<img src='upcimg.php?upc=' . $barcode . '' />';
68       $output .= '</div>';
69 
73       $result = XMLRPC_request('dev.upcdatabase.com', '/rpc', 'lookupUPC', array(XMLRPC_prepare($barcode)));
74 //       if ($debug) var_dump($result);
75       echo getImages($result[1]['description']);
76       if ($result[1]['found']) {
77         extract($result[1], EXTR_PREFIX_ALL, 'barcode');
78         $output .= <<<_HTML
79         <div id='info'>
80           <table align='center'>
81             <tr>
82               <td class='title'>Country</td>
83               <td>$barcode_issuerCountry</td>
84             </tr>
85             <tr>
86               <td class='title'>Description</td>
87               <td>$barcode_description</td>
88             </tr>
89             <tr>
90               <td class='title'>Size</td>
91               <td>$barcode_size</td>
92             </tr>
93           </table>
94           <a href='http://www.upcdatabase.com/editform.asp?upc=$barcode'>Modify this entry</a>
95           <a href='http://www.upcdatabase.com/deleteform.asp?upc=$barcode'>Delete this entry</a>
96         </div>
97 _HTML;
98       }
99       else {
100         $output .= 'Product Not Found!<br />';
101         $output .= '<a href='http://www.upcdatabase.com/addform.asp?upc=' . $barcode . ''>Add this item to the database</a>';
102       }
103       break;
104 
105     case 'isbn':
109       $xml = parseXML('http://isbndb.com/api/books.xml?access_key=' . ISBNKEY . '&index1=isbn&results=texts&value1=' . $barcode);
110 //       var_dump($xml);
111 
112       // Sometimes, the long title is non-existant, so fall back onto the short title
113       if (strlen($xml->BookList->BookData->TitleLong) != 0) {
117         $title = $xml->BookList->BookData->TitleLong;
118       }
119       else {
123         $title = $xml->BookList->BookData->Title;
124       }
128       $author = $xml->BookList->BookData->AuthorsText;
132       $publisher = $xml->BookList->BookData->PublisherText;
136       $summary = $xml->BookList->BookData->Summary;
140       $isbn = $xml->BookList->BookData['isbn'];
141 
145       $output = '';
146       $output .= '<div id='upc'>';
147       $output .= '<img src='upcimg.php?upc=' . $barcode . '' />';
148       $output .= '</div>';
149       $output .= <<<_HTML
150       <div id='info'>
151         <table align='center'>
152           <tr>
153             <td class='title'>Title</td>
154             <td>$title</td>
155           </tr>
156           <tr>
157             <td class='title'>Author</td>
158             <td>$author</td>
159           </tr>
160           <tr>
161             <td class='title'>Publisher</td>
162             <td>$publisher</td>
163           </tr>
164           <tr>
165             <td colspan='2'>$summary</td>
166           </tr>
167           <tr>
168             <td class='title'>Buy</td>
169             <td>
170               <!-- Amazon.com uses the ISBN-10 code, so send it that -->
171               <a href='http://www.amazon.com/exec/obidos/ASIN/$isbn/'>Amazon.com</a><br />
172               <!-- Everyone else uses the ISBN-13 code, so send them that -->
173               <a href='http://search.barnesandnoble.com/booksearch/isbninquiry.asp?ean=$barcode'>Barnes & Noble</a><br />
174               <a href='http://www.booksamillion.com/ncom/books?type=isbn&find=$barcode'>Books-A-Million</a><br />
175               <a href='http://www.google.com/products?q=$barcode'>Google Product Search</a>
176             </td>
177           </tr>
178         </table>
179       </div>
180 _HTML;
181       break;
182   }
183 
184   return $output;
185 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
