.TH "include/barcode.inc" 3 "4 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/barcode.inc \- Functions for the handling of different barcodes. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcheckBarcode\fP ($barcode)"
.br
.ti -1c
.RI "\fBgetBarcodeInfo\fP ($barcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for the handling of different barcodes. 

This file currently deals with the handling of barcodes and getting the information associated with them. 
.PP
Definition in file \fBbarcode.inc\fP.
.SH "Function Documentation"
.PP 
.SS "checkBarcode ($ barcode)"
.PP
Checks to see if a valid, handalable, barcode was entered. 
.PP
\fBParameters:\fP
.RS 4
\fI$barcode\fP The Barcode to be checked 
.RE
.PP
\fBReturns:\fP
.RS 4
The type of barcode entered if valid, FALSE if it is not 
.RE
.PP

.PP
Definition at line 16 of file barcode.inc.
.PP
References XMLRPC_prepare(), and XMLRPC_request().
.PP
.nf
16                                 {
20   $result = XMLRPC_request('dev.upcdatabase.com', '/rpc', 'lookupUPC', array(XMLRPC_prepare($barcode)));
21   if ($result[1] != 'Error: Invalid length') {
22     if (strlen($barcode) == 12) {
23       return 'upca';
24     }
25     else if (strlen($barcode) == 13) {
26       return 'ean13';
27     }
28     else {
29       return FALSE;
30     }
31   }
32   else {
33     return FALSE;
34   }
35 }
.fi
.PP
.SS "getBarcodeInfo ($ barcode)"
.PP
Output Barcode Info 
.PP
\fBParameters:\fP
.RS 4
\fI$barcode\fP The barcode to lookup 
.RE
.PP
\fBReturns:\fP
.RS 4
HTML code to create the info area 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBcheckBarcode\fP 
.RE
.PP

.PP
Definition at line 43 of file barcode.inc.
.PP
References getImages(), XMLRPC_prepare(), and XMLRPC_request().
.PP
.nf
43                                   {
47   $output = '';
48   $output .= '<div id='upc'>';
49   $output .= '<img src='upcimg.php?upc=' . $barcode . '' />';
50   $output .= '</div>';
51 
55   $result = XMLRPC_request('dev.upcdatabase.com', '/rpc', 'lookupUPC', array(XMLRPC_prepare($barcode)));
56 //   if ($debug) var_dump($result);
57   echo getImages($result[1]['description']);
58   if ($result[1]['found']) {
59     extract($result[1], EXTR_PREFIX_ALL, 'barcode');
60     $output .= <<<_HTML
61     <div id='info'>
62       <table align='center'>
63         <tr>
64           <td class='title'>Country</td>
65           <td>$barcode_issuerCountry</td>
66         </tr>
67         <tr>
68           <td class='title'>Description</td>
69           <td>$barcode_description</td>
70         </tr>
71         <tr>
72           <td class='title'>Size</td>
73           <td>$barcode_size</td>
74         </tr>
75       </table>
76       <a href='http://www.upcdatabase.com/editform.asp?upc=$barcode'>Modify this entry</a>
77       <a href='http://www.upcdatabase.com/deleteform.asp?upc=$barcode'>Delete this entry</a>
78     </div>
79 _HTML;
80   }
81   else {
82     $output .= 'Product Not Found!<br />';
83     $output .= '<a href='http://www.upcdatabase.com/addform.asp?upc=' . $barcode . ''>Add this item to the database</a>';
84   }
85 
86   return $output;
87 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
