.TH "bug" 3 "26 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List
 
.IP "\fBFile \fBxmlrpc.inc\fP \fP" 1c
Generates the following error on DreamHost servers (and possible others) at different places in the file:
.br
 Warning: Call-time pass-by-reference has been deprecated; If you would like to pass it by reference, modify the declaration of xml_set_object(). If you would like to enable call-time pass-by-reference, you can set allow_call_time_pass_reference to true in your INI file. in /home/.zerlina/dkeenan/upc.dankeenan.org/xmlrpc.inc 
.PP

