.TH "form.inc" 3 "21 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
form.inc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetEntryForm\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for outputting the Barcode entry form 
.PP
Definition in file \fBform.inc\fP.
.SH "Function Documentation"
.PP 
.SS "getEntryForm ()"
.PP
Creates an entry form for UPCs (and eventually other types of Barcodes 
.PP
\fBReturns:\fP
.RS 4
The Barcode entry form 
.RE
.PP

.PP
String containing the Barcode entry form 
.PP
Definition at line 10 of file form.inc.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
