.TH "include/form.inc" 3 "26 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/form.inc \- Functions for outputting the Barcode entry form. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetEntryForm\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for outputting the Barcode entry form. 

This file currently contains functions that relate to various forms. As there is currently only one form, this file may seem redundant. However, it stays for the sake of forward compatability. 
.PP
Definition in file \fBform.inc\fP.
.SH "Function Documentation"
.PP 
.SS "getEntryForm ()"
.PP
Creates an entry form for UPCs (and eventually other types of Barcodes 
.PP
\fBReturns:\fP
.RS 4
The Barcode entry form 
.RE
.PP

.PP
String containing the Barcode entry form 
.PP
Definition at line 14 of file form.inc.
.PP
.nf
14                         {
18   $form = <<<_HTML
19               <form action='index.php' method='get' id='codeentry'>
20                 <fieldset>
21                   <label>UPC:</label><input type='text' name='upc' /><br />
22                   <input type='submit' value='Submit' />
23                 </fieldset>
24               </form>
25 _HTML;
26 
27   return $form;
28 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
