.TH "index.php" 3 "22 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$debug\fP = TRUE"
.br
.ti -1c
.RI "\fB$upc\fP = $_GET['upc']"
.br
.in -1c
.SH "Detailed Description"
.PP 
Returns info on a given UPC Barcode 
.PP
Definition in file \fBindex.php\fP.
.SH "Variable Documentation"
.PP 
.SS "$debug = TRUE"
.PP
Set to TRUE to output debug info 
.PP
Definition at line 14 of file index.php.
.PP
Referenced by XMLRPC_debug_print().
.SS "$upc = $_GET['upc']"
.PP
Holds the barcode entered 
.PP
\fBNote:\fP
.RS 4
Can hold any barcode, but named $upc for ease of entry 
.RE
.PP

.PP
Definition at line 61 of file index.php.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
