.TH "isbnapi" 3 "7 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isbnapi \- ISBNdb API
\fBNote:\fP
.RS 4
You \fBmust\fP create an API Key at https://isbndb.com/account/dev/keys/generate.html before you can use this function.
.RE
.PP
All calls to the API return data in an \fBXML\fP format. A request of 
.PP
.nf
 http://isbndb.com/api/books.xml?access_key=12345678&index1=isbn&value1=0596002068

.fi
.PP
 would return the following: 
.PP
.nf
 <?xml version='1.0' encoding='UTF-8'?>
 <ISBNdb server_time='2005-02-25T23:03:41'>
  <BookList total_results='1' page_size='10' page_number='1' shown_results='1'>
   <BookData book_id='somebook' isbn='0123456789'>
    <Title>Interesting Book</Title>
    <TitleLong>Interesting Book: Read it or else..</TitleLong>
    <AuthorsText>John Doe</AuthorsText>
    <PublisherText>Acme Publishing</PublisherText>
   </BookData>
  </BookList>
 </ISBNdb>

.fi
.PP
 
.PP
\fBSee also:\fP
.RS 4
https://isbndb.com/docs/api/ 
.PP
https://isbndb.com/ 
.RE
.PP

