.TH "pear.inc" 3 "22 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pear.inc \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Makes PEAR work with extentions installed in the home directory. 
.PP
Definition in file \fBpear.inc\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
