.TH "include/pear.inc" 3 "5 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pear.inc \- Makes PEAR work with extentions installed in the home directory. 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHOME_PEAR_DIR\fP "
.br
.in -1c
.SH "Detailed Description"
.PP 
Makes PEAR work with extentions installed in the home directory. 

Most shared hosts do not allow user installation of system-wide PEAR extentions, so this file allows it to work with extentions installed in the user's home directory. To make this work, you need to set the HOME_PEAR_DIR constant to the path where your PEAR extentions are installed. See that documentation for more info. 
.PP
Definition in file \fBpear.inc\fP.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHOME_PEAR_DIR\fP"
.PP
The location of PEAR extentions in the home directory. This is usually \fB/home/<username>/pear/php\fP 
.PP
Definition at line 16 of file pear.inc.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
