.TH "include/product.inc" 3 "7 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/product.inc \- Functions to output Product Info. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetImages\fP ($product)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to output Product Info. 

Various pieces of info gleamed from the web will be handled by functions contained in this file. Currently, it only handles getting product images 
.PP
Definition in file \fBproduct.inc\fP.
.SH "Function Documentation"
.PP 
.SS "getImages ($ product)"
.PP
Gets Appropriate Images from google Image Search 
.PP
\fBParameters:\fP
.RS 4
\fI$product\fP The product to get images for 
.RE
.PP
\fBReturns:\fP
.RS 4
HTML code to output product images 
.RE
.PP

.PP
Definition at line 15 of file product.inc.
.PP
References fget().
.PP
Referenced by getBarcodeInfo().
.PP
.nf
15                              {
19   $json = json_decode(fget('http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=' . urlencode($product) . '&rsz=large'));
20   // Hack to get Indexes working
21   if ($_GET['index']) {
22     $currentIndex = (int) $_GET['index'];
23   }
24   else {
25     $currentIndex = 0;
26   }
27   $prevIndex = $currentIndex - 1;
28   $nextIndex = $currentIndex + 1;
29   $i = 0;
30   $getText = '?';
31   foreach ($_GET as $item) {
32     if (key($_GET) != 'index') {
33       if ($i == 0) {
34         $getText .= key($_GET) . '=' . $item;
35       }
36       else {
37         $getText .= '&' . key($_GET) . '=' . $item;
38       }
39     }
40     next($_GET);
41     $i++;
42   }
43 
44   $originalContextUrl = $json->responseData->results[$currentIndex]->originalContextUrl;
45   $imgSrc = $json->responseData->results[$currentIndex]->tbUrl;
46   $visibleUrl = $json->responseData->results[$currentIndex]->visibleUrl;
47 
51   $output = '<div id=\'prodimg\'>';
52   // Only display previous button if there are previous values
53   if ($currentIndex > 0) {
54     $output .= '<a href=\'{$getText}&index={$prevIndex}\'><img src=\'images/arrows/left.png\' alt=\'Previous Image\' title=\'Previous Image\' /></a>';
55   }
56   $output .= '<a href=\'{$originalContextUrl}\' target=\'_blank\'><img src=\'{$imgSrc}\' alt=\'Image of $product From {$visibleUrl}\' title=\'Image of $product From {$visibleUrl}\' id=\'prodimg\'></a>';
57   // Only display next button if there are more images
58   if ($currentIndex < count($json->responseData->results) - 1) {
59    $output .= '<a href=\'{$getText}&index={$nextIndex}\'> <img src=\'images/arrows/right.png\' alt=\'Next Image\' title=\'Next Image\' /></a><br /><a href=\'aboutimages.html\' target=\'_blank\' onclick=\'popup(this.href, 200, 300); return false;\'>About this image</a></div>';
60   }
61 
62   return $output;
63 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
