.TH "include/product.inc" 3 "7 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/product.inc \- Functions to output Product Info. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetImages\fP ($product)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to output Product Info. 

Various pieces of info gleamed from the web will be handled by functions contained in this file. Currently, it only handles getting product images 
.PP
Definition in file \fBproduct.inc\fP.
.SH "Function Documentation"
.PP 
.SS "getImages ($ product)"
.PP
Gets Appropriate Images from google Image Search 
.PP
\fBParameters:\fP
.RS 4
\fI$product\fP The product to get images for 
.RE
.PP
\fBReturns:\fP
.RS 4
HTML code to output product images
.RE
.PP
\fBTodo\fP
.RS 4
Get Book Covers for books (Items with ISBN Numbers) 
.RE
.PP

.PP
Definition at line 17 of file product.inc.
.PP
References fget().
.PP
Referenced by getBarcodeInfo().
.PP
.nf
17                              {
21   $json = json_decode(fget('http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=' . urlencode($product) . '&rsz=large'));
22   // Hack to get Indexes working
23   if ($_GET['index']) {
24     $currentIndex = (int) $_GET['index'];
25   }
26   else {
27     $currentIndex = 0;
28   }
29   $prevIndex = $currentIndex - 1;
30   $nextIndex = $currentIndex + 1;
31   $i = 0;
32   $getText = '?';
33   foreach ($_GET as $item) {
34     if (key($_GET) != 'index') {
35       if ($i == 0) {
36         $getText .= key($_GET) . '=' . $item;
37       }
38       else {
39         $getText .= '&' . key($_GET) . '=' . $item;
40       }
41     }
42     next($_GET);
43     $i++;
44   }
45 
46   $originalContextUrl = $json->responseData->results[$currentIndex]->originalContextUrl;
47   $imgSrc = $json->responseData->results[$currentIndex]->tbUrl;
48   $visibleUrl = $json->responseData->results[$currentIndex]->visibleUrl;
49 
53   $output = '<div id=\'prodimg\'>';
54   // Only display previous button if there are previous values
55   if ($currentIndex > 0) {
56     $output .= '<a href=\'{$getText}&index={$prevIndex}\'><img src=\'images/arrows/left.png\' alt=\'Previous Image\' title=\'Previous Image\' /></a>';
57   }
58   $output .= '<a href=\'{$originalContextUrl}\' target=\'_blank\'><img src=\'{$imgSrc}\' alt=\'Image of $product From {$visibleUrl}\' title=\'Image of $product From {$visibleUrl}\' id=\'prodimg\'></a>';
59   // Only display next button if there are more images
60   if ($currentIndex < count($json->responseData->results) - 1) {
61    $output .= '<a href=\'{$getText}&index={$nextIndex}\'> <img src=\'images/arrows/right.png\' alt=\'Next Image\' title=\'Next Image\' /></a><br /><a href=\'aboutimages.html\' target=\'_blank\' onclick=\'popup(this.href, 200, 300); return false;\'>About this image</a></div>';
62   }
63 
64   return $output;
65 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
