.TH "include/product.inc" 3 "4 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/product.inc \- Functions to output Product Info. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetImages\fP ($product)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to output Product Info. 

Various pieces of info gleamed from the web will be handled by functions contained in this file. Currently, it only handles getting product images 
.PP
Definition in file \fBproduct.inc\fP.
.SH "Function Documentation"
.PP 
.SS "getImages ($ product)"
.PP
Gets Appropriate Images from google Image Search 
.PP
\fBParameters:\fP
.RS 4
\fI$product\fP The product to get images for 
.RE
.PP
\fBReturns:\fP
.RS 4
HTML code to output product images 
.RE
.PP
\fBTodo\fP
.RS 4
Make images more accurate 
.RE
.PP

.PP
Definition at line 16 of file product.inc.
.PP
References fget().
.PP
Referenced by getBarcodeInfo().
.PP
.nf
16                              {
20   $json = json_decode(fget('http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=' . urlencode($product)));
24   $imgpath = $json->responseData->results[0]->tbUrl;
28   $imgsource = $json->responseData->results[0]->visibleUrl;
32   $imgsourceurl = $json->responseData->results[0]->tbUrl;
36   $imgcontext = $json->responseData->results[0]->originalContextUrl;
40   $output = '';
41   $output = <<<_HTML
42     <div id='prodimg'>
43       <a href='$imgcontext' target='_blank'>
44         <img src='$imgpath' alt='Image of $product From $imgsource' title='Image of $product From $imgsource'>
45       </a><br />
46       <a href='aboutimages.html' target='_blank' onclick='popup(this.href, 200, 300); return false;'>About this image</a>
47     </div>
48 _HTML;
49 
50   return $output;
51 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
