.TH "todo" 3 "5 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBpage \fBMain Page\fP \fP" 1c
Make a Firefox/greasemonkey plugin to access site if the user types in an ISBN or UPC.
.PP
.PP
.PP
 
.IP "\fBMember \fBgetImages\fP \fP" 1c
Make images more accurate 
.PP
Add left and right arrows to choose image to show 
.PP

