.TH "todo" 3 "21 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBpage \fBMain Page\fP \fP" 1c
Make this support everyhting Image_Barcode supports:
.IP "\(bu" 2
Code 39
.IP "\(bu" 2
Code 128
.IP "\(bu" 2
EAN 13
.IP "\(bu" 2
INT 25
.IP "\(bu" 2
PostNet
.IP "\(bu" 2
UPCA 
.PP
.PP
Fix errors 
.PP
Add possible product images
.PP
.PP

