.TH "todo" 3 "27 Apr 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBpage \fBMain Page\fP \fP" 1c
Make this support everyhting Image_Barcode supports:
.IP "\(bu" 2
Code 39
.IP "\(bu" 2
Code 128
.IP "\(bu" 2
EAN 13
.IP "  \(bu" 4
\fBDone!\fP 
.PP

.IP "\(bu" 2
INT 25
.IP "\(bu" 2
PostNet
.IP "  \(bu" 4
\fBWill probably not be done, as it can not be read by most barcode scanners and has no practical purpose\fP
.PP

.IP "\(bu" 2
UPCA
.IP "  \(bu" 4
\fBDone!\fP 
.PP

.PP
.PP
Fix errors
.PP
.PP

