.TH "upcimg.php" 3 "26 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upcimg.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Creates an image of the barcode using Image_Barcode 
.PP
\fBSee also:\fP
.RS 4
http://pear.php.net/package/Image_Barcode 
.PP
http://pear.php.net/manual/en/package.images.image-barcode.php 
.RE
.PP

.PP
Definition in file \fBupcimg.php\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
