.TH "upcimg.php" 3 "4 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upcimg.php \- Creates an image of the barcode using Image_Barcode. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Creates an image of the barcode using Image_Barcode. 

Uses the PHP Imagage_Barcode Extention to generate barcode images for the entered barcode. This may need to be (it can't cause any harm) used in compination with \fBpear.inc\fP on shared hosts and other environments. 
.PP
\fBSee also:\fP
.RS 4
http://pear.php.net/package/Image_Barcode 
.PP
http://pear.php.net/manual/en/package.images.image-barcode.php 
.RE
.PP

.PP
Definition in file \fBupcimg.php\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
