.TH "XML" 3 "22 Apr 2008" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XML \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXML\fP ($data=null)"
.br
.ti -1c
.RI "\fBdestruct\fP ()"
.br
.ti -1c
.RI "\fBparse\fP ($data)"
.br
.ti -1c
.RI "\fBopen\fP ($parser, $tag, $attributes)"
.br
.ti -1c
.RI "\fBdata\fP ($parser, $data)"
.br
.ti -1c
.RI "\fBclose\fP ($parser, $tag)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$parser\fP"
.br
.ti -1c
.RI "\fB$document\fP"
.br
.ti -1c
.RI "\fB$current\fP"
.br
.ti -1c
.RI "\fB$parent\fP"
.br
.ti -1c
.RI "\fB$parents\fP"
.br
.ti -1c
.RI "\fB$last_opened_tag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file xmlrpc.inc.
.SH "Member Function Documentation"
.PP 
.SS "XML::XML ($ data = \fCnull\fP)"
.PP
Definition at line 89 of file xmlrpc.inc.
.SS "XML::destruct ()"
.PP
Definition at line 99 of file xmlrpc.inc.
.SS "XML::parse ($ data)"
.PP
Definition at line 103 of file xmlrpc.inc.
.SS "XML::open ($ parser, $ tag, $ attributes)"
.PP
Definition at line 112 of file xmlrpc.inc.
.PP
References count_numeric_items(), and data().
.SS "XML::data ($ parser, $ data)"
.PP
Definition at line 149 of file xmlrpc.inc.
.PP
Referenced by close(), and open().
.SS "XML::close ($ parser, $ tag)"
.PP
Definition at line 156 of file xmlrpc.inc.
.PP
References data().
.SH "Member Data Documentation"
.PP 
.SS "XML::$parser"
.PP
Definition at line 81 of file xmlrpc.inc.
.SS "XML::$document"
.PP
Definition at line 82 of file xmlrpc.inc.
.SS "XML::$current"
.PP
Definition at line 83 of file xmlrpc.inc.
.SS "XML::$parent"
.PP
Definition at line 84 of file xmlrpc.inc.
.SS "XML::$parents"
.PP
Definition at line 85 of file xmlrpc.inc.
.SS "XML::$last_opened_tag"
.PP
Definition at line 87 of file xmlrpc.inc.

.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
