.TH "include/xmlparse.inc" 3 "8 May 2008" "Version 0.2" "UPC Lookup" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/xmlparse.inc \- Functions to parse \fBXML\fP data. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBparseXML\fP ($url)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to parse \fBXML\fP data. 

Functions to parse \fBXML\fP data. Specifaclly created for use with isbndb.com 
.PP
Definition in file \fBxmlparse.inc\fP.
.SH "Function Documentation"
.PP 
.SS "parseXML ($ url)"
.PP
Parse \fBXML\fP Data from the given URL 
.PP
\fBParameters:\fP
.RS 4
\fI$url\fP Location of \fBXML\fP data 
.RE
.PP
\fBReturns:\fP
.RS 4
Object containing parsed \fBXML\fP data 
.RE
.PP

.PP
Definition at line 15 of file xmlparse.inc.
.PP
References fget().
.PP
Referenced by getBarcodeInfo().
.PP
.nf
15                         {
19   $xmlstr = fget($url);
23   $xml = new SimpleXMLElement($xmlstr);
24 
25   return $xml;
26 }
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for UPC Lookup from the source code.
