XML Class Reference
Public Member Functions
XML ($data=null)
destruct ()
parse ($data)
open ($parser, $tag, $attributes)
data ($parser, $data)
close ($parser, $tag)
Public Attributes
$parser
$document
$current
$parent
$parents
$last_opened_tag
Detailed Description
Definition at line 80 of file xmlrpc.inc.
Member Function Documentation
XML::XML ($ data = null)
Definition at line 89 of file xmlrpc.inc.
89                           {
90     $this->parser = xml_parser_create();
91 
92     xml_parser_set_option ($this->parser, XML_OPTION_CASE_FOLDING, 0);
93     xml_set_object($this->parser, &$this);
94     xml_set_element_handler($this->parser, "open", "close");
95     xml_set_character_data_handler($this->parser, "data");
96 #   register_shutdown_function(array(&$this, 'destruct'));
97   }
XML::destruct ()
Definition at line 99 of file xmlrpc.inc.
99                      {
100     xml_parser_free($this->parser);
101   }
XML::parse ($ data)
Definition at line 103 of file xmlrpc.inc.
103                        {
104     $this->document = array();
105     $this->parent = &$this->document;
106     $this->parents = array();
107     $this->last_opened_tag = NULL;
108     xml_parse($this->parser, $data);
109     return $this->document;
110   }
XML::open ($ parser, $ tag, $ attributes)
Definition at line 112 of file xmlrpc.inc.
References count_numeric_items(), and data().
112                                            {
113     #echo "Opening tag $tag<br>\n";
114     $this->data = "";
115     $this->last_opened_tag = $tag; #tag is a string
116     if(array_key_exists($tag, $this->parent)){
117       #echo "There's already an instance of '$tag' at the current level ($level)<br>\n";
118       if(is_array($this->parent[$tag]) and array_key_exists(0, $this->parent[$tag])){ #if the keys are numeric
119         #need to make sure they're numeric (account for attributes)
120         $key = count_numeric_items($this->parent[$tag]);
121         #echo "There are $key instances: the keys are numeric.<br>\n";
122       }else{
123         #echo "There is only one instance. Shifting everything around<br>\n";
124         $temp = &$this->parent[$tag];
125         unset($this->parent[$tag]);
126         $this->parent[$tag][0] = &$temp;
127 
128         if(array_key_exists("$tag attr", $this->parent)){
129           #shift the attributes around too if they exist
130           $temp = &$this->parent["$tag attr"];
131           unset($this->parent["$tag attr"]);
132           $this->parent[$tag]["0 attr"] = &$temp;
133         }
134         $key = 1;
135       }
136       $this->parent = &$this->parent[$tag];
137     }else{
138       $key = $tag;
139     }
140     if($attributes){
141       $this->parent["$key attr"] = $attributes;
142     }
143 
144     $this->parent[$key] = array();
145     $this->parent = &$this->parent[$key];
146     array_unshift($this->parents, &$this->parent);
147   }
XML::data ($ parser, $ data)
Definition at line 149 of file xmlrpc.inc.
Referenced by close(), and open().
149                                {
150     #echo "Data is '", htmlspecialchars($data), "'<br>\n";
151     if($this->last_opened_tag != NULL){
152       $this->data .= $data;
153     }
154   }
XML::close ($ parser, $ tag)
Definition at line 156 of file xmlrpc.inc.
References data().
156                                {
157     #echo "Close tag $tag<br>\n";
158     if($this->last_opened_tag == $tag){
159       $this->parent = $this->data;
160       $this->last_opened_tag = NULL;
161     }
162     array_shift($this->parents);
163     $this->parent = &$this->parents[0];
164   }
Member Data Documentation
XML::$parser
Definition at line 81 of file xmlrpc.inc.
XML::$document
Definition at line 82 of file xmlrpc.inc.
XML::$current
Definition at line 83 of file xmlrpc.inc.
XML::$parent
Definition at line 84 of file xmlrpc.inc.
XML::$parents
Definition at line 85 of file xmlrpc.inc.
XML::$last_opened_tag
Definition at line 87 of file xmlrpc.inc.
The documentation for this class was generated from the following file:
include/xmlrpc.inc